# Makefile for {{ projectLanguage }} project
TOP_DIR=$(shell dirname $(abspath $(firstword $(MAKEFILE_LIST))))

# Variables
GIT_PROVIDER := {{ gitProvider }}
PORJECGT_USER := {{ projectUser }}
PROJECT_NAME := {{ projectLanguage }}-{{ projectName }}-{{ projectType }}

# Functions

# Targets

.DEFAULT_GOAL := help

.PHONY: help
help:
	@echo "Usage: make [target]"
	@echo "Targets:"
	@echo "	 help: Show this help message"
	@echo "	 install: Install packages for the project"
	@echo "	 update: Update packages for the project"
	@echo "	 build: Build the project"
	@echo "	 run: Run the project"
	@echo "	 test: Test the project"
	@echo "	 lint: Lint the project"
	@echo "	 clean: Clean the project"

.PHONY: install
install:
	@echo "Install packages for the project"
	npm install

.PHONY: update
update:
	@echo "Update packages for the project"
	npm update

.PHONY: build
build:
	@echo "Build the project"
	npm run build

.PHONY: run
run:
	@echo "Run the project"
	npm run start

.PHONY: test
test:
	@echo "Test the project"
	npm run test

.PHONY: lint
lint:
	@echo "Lint the project"
	npm run lint

.PHONY: clean
clean:
	@echo "Clean the project"
	rm -rf node_modules dist coverage .nyc_output .eslintcache .cache .jest