#!/bin/bash

# Get the current directory
CURRENT_DIR=$(dirname "$0")

# Find all subdirectories in the current directory
SUBDIRECTORIES=$(find "$CURRENT_DIR" -type d -not -path '*/dist*' -not -path '*/node_modules*')

# Loop through subdirectories
for DIR in $SUBDIRECTORIES; do
  # Exclude the current directory
  if [[ "$DIR" != "$CURRENT_DIR" ]]; then
    INDEX_FILE="$DIR/index.ts"
    INDEX_FILE_EXISTS=false

    # Check if the index.ts file exists in the directory
    if [ -f "$INDEX_FILE" ]; then
      INDEX_FILE_EXISTS=true
    fi

    # List TypeScript files in the subdirectory (excluding index.ts, spec.ts, and test.ts) and sort them
    TS_FILES=$(find "$DIR" -maxdepth 1 -type f \( -name "*.ts" ! -name "index.ts" ! -name "*spec.ts" ! -name "*test.ts" \) | sort)

    # If index.ts exists and there are other .ts files, update the index file
    if [ "$INDEX_FILE_EXISTS" = true ] && [ ! -z "$TS_FILES" ]; then
      # Create or overwrite the index file
      echo "// This file is autogenerated by the script." > "$INDEX_FILE"
      echo "// Do not edit this file directly." >> "$INDEX_FILE"
      echo "import 'reflect-metadata';" >> "$INDEX_FILE"

      # Loop through TypeScript files and add imports to the index file
      for FILE_PATH in $TS_FILES; do
        RELATIVE_PATH="${FILE_PATH#"$DIR"/}"
        FILE_NAME_WITHOUT_EXT=$(basename "$RELATIVE_PATH" .ts)
        echo "export * from './$FILE_NAME_WITHOUT_EXT';" >> "$INDEX_FILE"
      done

      echo "Index file generated for $DIR with sorted imports of TypeScript files."
    elif [ "$INDEX_FILE_EXISTS" = true ]; then
      # Remove the index.ts file if it's the only file in the directory
      rm "$INDEX_FILE"
      echo "Removed index file from $DIR."
    fi
  fi
done

# #!/bin/bash

# # Get the current directory
# CURRENT_DIR=$(dirname "$0")

# # Find all subdirectories in the current directory
# SUBDIRECTORIES=$(find "$CURRENT_DIR" -type d -not -path '*/dist*' -not -path '*/node_modules*')

# # Loop through subdirectories
# for DIR in $SUBDIRECTORIES; do
#   # Exclude the current directory
#   if [[ "$DIR" != "$CURRENT_DIR" ]]; then
#     INDEX_FILE="$DIR/index.ts"

#     # Check if the index.ts file exists in the directory
#     if [ -f "$INDEX_FILE" ]; then
#       # Remove the index.ts file
#       rm "$INDEX_FILE"
#       echo "Removed index file from $DIR."
#     fi
#   fi
# done