// This file is autogenerated by the script.
// Do not edit this file directly.
import 'reflect-metadata';
export * from './task-description-gherkin.entity';
export * from './task-description-string.entity';
