# Makefile for {{ projectLanguage }} project
TOP_DIR=$(shell dirname $(abspath $(firstword $(MAKEFILE_LIST))))

# Variables
GIT_PROVIDER := {{ gitProvider }}
PORJECGT_USER := {{ projectUser }}
PROJECT_NAME := {{ projectLanguage }}-{{ projectName }}-{{ projectType }}

# Functions

# Targets

.DEFAULT_GOAL := help

.PHONY: help
help:
	@echo "Usage: make [target]"
	@echo "Targets:"
	@echo "	 help: Show this help message"
	@echo "	 install: Install packages for the project"
	@echo "	 update: Update packages for the project"
	@echo "	 build: Build the project"
	@echo "	 run: Run the project"
	@echo "	 test: Test the project"
	@echo "	 lint: Lint the project"
	@echo "	 clean: Clean the project"

.PHONY: install
install:
	@echo "Install packages for the project"

.PHONY: update
update:
	@echo "Update packages for the project"

.PHONY: build
build:
	@echo "Build the project"

.PHONY: run
run:
	@echo "Run the project"
	python3 main.py

.PHONY: test
test:
	@echo "Test the project"
	python3 -m pytest -s -v test_main.py

.PHONY: lint
lint:
	@echo "Lint the project"
	python3 -m pylint main.py

.PHONY: clean
clean:
	@echo "Clean the project"
	rm -rf __pycache__ .pytest_cache