export const DEFAULT_DOCUMENT_FILE_PATH = '.';
export const DOCUMENT_TEMPLATE_TYPES = [
  // 'api',
  // 'architecture',
  // 'changelog',
  // 'code-of-conduct',
  // 'contributing',
  // 'deployment-plan',
  // 'high-level-design',
  // 'issue-template',
  // 'license',
  // 'low-level-design',
  // 'product-backlog',
  // 'product-design',
  // 'product-requirements',
  // 'pull-request-template',
  // 'readme',
  // 'release-notes',
  // 'release-plan',
  // 'roadmap',
  // 'security',
  // 'software-design',
  // 'software-requirements',
  // 'support',
  // 'todo',
  // 'test-plan',
  // 'test-report',
  // 'user-guide',
  // 'user-stories',
  // 'use-case',
  // 'unified-modelling-language',
  // 'versioning',
  // 'wiki',
  'deployment_plan',
  'hld',
  'note',
  'prd',
  'release_note',
  'release_plan',
  'rfc',
  'sdd',
  'test_case',
  'test_plan',
  'uml',
];

export const PROJECT_DOCUMENT_DIRECTORIES = [
  'agile-board',
  'design-document',
  'test-plan',
  'test-report',
  'release-plan',
  'release-note',
  'note',
];

export const PROJECT_NOTE_FILES = [
  // 'changelog',
  // 'code-of-conduct',
  // 'contributing',
  // 'issue-template',
  // 'license',
  // 'pull-request-template',
  // 'readme',
  // 'roadmap',
  // 'security',
  // 'support',
  // 'todo',
  // 'user-guide',
  // 'versioning',
  // 'wiki',
  'environment_setup',
  'project_setup',
  'project_structure',
  'project_configuration',
  'project_implementation',
  'project_testing',
  'project_deployment',
  'project_documentation',
  'project_maintenance',
  'project_monitoring',
  'project_security',
  'project_performance',
];
