export const STORAGE_DEVICE_TYPES = ['file', 'database'];
export const DEFAULT_STORAGE_DEVICE_TYPE = STORAGE_DEVICE_TYPES[0];

export const FILE_STORAGE_DEVICE_TYPES = ['json', 'yaml', 'csv', 'md'];
export const DEFAULT_FILE_STORAGE_DEVICE_TYPE = FILE_STORAGE_DEVICE_TYPES[0];
export const DEFAULT_FILE_STORAGE_EXTENSION = FILE_STORAGE_DEVICE_TYPES[0];

export const DATABASE_STORAGE_DEVICE_TYPES = [
  'memory',
  'sqlite',
  'mongo',
  'postgres',
];
export const DEFAULT_DATABASE_STORAGE_DEVICE_TYPE =
  DATABASE_STORAGE_DEVICE_TYPES[0];

export const STORAGE_FILE_TYPE = ['single', 'multiple'];
export const DEFAULT_STORAGE_FILE_TYPE = STORAGE_FILE_TYPE[1];

const DEFAULT_ROOT_PROJECT_PATH = '.';

export const DEFAULT_PROJECT_NAME = 'scrum-project';
export const DEFAULT_PROJECT_FILE_NAME = 'project.json';
export const DEFAULT_PROJECT_PATH = `${DEFAULT_ROOT_PROJECT_PATH}/.${DEFAULT_PROJECT_NAME}`;
export const DEFAULT_PROJECT_FILE_PATH = `${DEFAULT_PROJECT_PATH}/${DEFAULT_PROJECT_FILE_NAME}`;

export const DEFAULT_TEAM_NAME = 'team';
export const DEFAULT_TEAM_FILE_NAME = 'team.json';
export const DEFAULT_TEAM_PATH = `${DEFAULT_PROJECT_PATH}/${DEFAULT_TEAM_NAME}`;
export const DEFAULT_TEAM_FILE_PATH = `${DEFAULT_TEAM_PATH}/${DEFAULT_TEAM_FILE_NAME}`;

export const DEFAULT_USER_NAME = 'user';
export const DEFAULT_USER_FILE_NAME = 'user.json';
export const DEFAULT_USER_PATH = `${DEFAULT_PROJECT_PATH}/${DEFAULT_USER_NAME}`;
export const DEFAULT_USER_FILE_PATH = `${DEFAULT_USER_PATH}/${DEFAULT_USER_FILE_NAME}`;

export const DEFAULT_ITERATION_NAME = 'iteration';
export const DEFAULT_ITERATION_FILE_NAME = 'iteration.json';
export const DEFAULT_ITERATION_PATH = `${DEFAULT_PROJECT_PATH}/${DEFAULT_ITERATION_NAME}`;
export const DEFAULT_ITERATION_FILE_PATH = `${DEFAULT_ITERATION_PATH}/${DEFAULT_ITERATION_FILE_NAME}`;

export const DEFAULT_TASK_NAME = 'task';
export const DEFAULT_TASK_FILE_NAME = 'task.json';
export const DEFAULT_TASK_PATH = `${DEFAULT_PROJECT_PATH}/${DEFAULT_TASK_NAME}`;
export const DEFAULT_TASK_FILE_PATH = `${DEFAULT_TASK_PATH}/${DEFAULT_TASK_FILE_NAME}`;

export const DEFAULT_METRIC_NAME = 'metric';
export const DEFAULT_METRIC_FILE_NAME = 'metric.json';
export const DEFAULT_METRIC_PATH = `${DEFAULT_PROJECT_PATH}/${DEFAULT_METRIC_NAME}`;
export const DEFAULT_METRIC_FILE_PATH = `${DEFAULT_METRIC_PATH}/${DEFAULT_METRIC_FILE_NAME}`;

export const DEFAULT_MSG_NAME = 'message';
export const DEFAULT_MSG_FILE_NAME = 'message.json';
export const DEFAULT_MSG_PATH = `${DEFAULT_PROJECT_PATH}/${DEFAULT_MSG_NAME}`;
export const DEFAULT_MSG_FILE_PATH = `${DEFAULT_MSG_PATH}/${DEFAULT_MSG_FILE_NAME}`;
