export type GENERAL_URL_TYPES =
  | 'WIKI'
  | 'JIRA'
  | 'CONFLUENCE'
  | 'GITHUB'
  | 'GITLAB'
  | 'BITBUCKET'
  | 'TRELLO'
  | 'ASANA'
  | 'NOTION'
  | 'PRD'
  | 'DESIGN'
  | 'HLD'
  | 'LLD'
  | 'CODE'
  | 'TEST'
  | 'DEPLOY'
  | 'RELEASE'
  | 'MONITOR'
  | 'OTHER'
  | 'EXTERNAL'
  | 'INTERNAL'
  | 'EXAMPLE';
export const GENERAL_URL_TYPE_ARRAY = [
  'WIKI',
  'JIRA',
  'CONFLUENCE',
  'GITHUB',
  'GITLAB',
  'BITBUCKET',
  'TRELLO',
  'ASANA',
  'NOTION',
  'PRD',
  'DESIGN',
  'HLD',
  'LLD',
  'CODE',
  'TEST',
  'DEPLOY',
  'RELEASE',
  'MONITOR',
  'OTHER',
  'EXTERNAL',
  'INTERNAL',
  'EXAMPLE',
];
export const DEFAULT_GENERAL_URL = 'OTHER';
export enum GENERAL_URL_ENUM {
  WIKI = 'WIKI',
  JIRA = 'JIRA',
  CONFLUENCE = 'CONFLUENCE',
  GITHUB = 'GITHUB',
  GITLAB = 'GITLAB',
  BITBUCKET = 'BITBUCKET',
  TRELLO = 'TRELLO',
  ASANA = 'ASANA',
  NOTION = 'NOTION',
  PRD = 'PRD',
  DESIGN = 'DESIGN',
  HLD = 'HLD',
  LLD = 'LLD',
  CODE = 'CODE',
  TEST = 'TEST',
  DEPLOY = 'DEPLOY',
  RELEASE = 'RELEASE',
  MONITOR = 'MONITOR',
  OTHER = 'OTHER',
  EXTERNAL = 'EXTERNAL',
  INTERNAL = 'INTERNAL',
  EXAMPLE = 'EXAMPLE',
}
export const GENERALURL_MAP = {
  [GENERAL_URL_ENUM.WIKI]: GENERAL_URL_ENUM.WIKI,
  [GENERAL_URL_ENUM.JIRA]: GENERAL_URL_ENUM.JIRA,
  [GENERAL_URL_ENUM.CONFLUENCE]: GENERAL_URL_ENUM.CONFLUENCE,
  [GENERAL_URL_ENUM.GITHUB]: GENERAL_URL_ENUM.GITHUB,
  [GENERAL_URL_ENUM.GITLAB]: GENERAL_URL_ENUM.GITLAB,
  [GENERAL_URL_ENUM.BITBUCKET]: GENERAL_URL_ENUM.BITBUCKET,
  [GENERAL_URL_ENUM.TRELLO]: GENERAL_URL_ENUM.TRELLO,
  [GENERAL_URL_ENUM.ASANA]: GENERAL_URL_ENUM.ASANA,
  [GENERAL_URL_ENUM.NOTION]: GENERAL_URL_ENUM.NOTION,
  [GENERAL_URL_ENUM.PRD]: GENERAL_URL_ENUM.PRD,
  [GENERAL_URL_ENUM.DESIGN]: GENERAL_URL_ENUM.DESIGN,
  [GENERAL_URL_ENUM.HLD]: GENERAL_URL_ENUM.HLD,
  [GENERAL_URL_ENUM.LLD]: GENERAL_URL_ENUM.LLD,
  [GENERAL_URL_ENUM.CODE]: GENERAL_URL_ENUM.CODE,
  [GENERAL_URL_ENUM.TEST]: GENERAL_URL_ENUM.TEST,
  [GENERAL_URL_ENUM.DEPLOY]: GENERAL_URL_ENUM.DEPLOY,
  [GENERAL_URL_ENUM.RELEASE]: GENERAL_URL_ENUM.RELEASE,
  [GENERAL_URL_ENUM.MONITOR]: GENERAL_URL_ENUM.MONITOR,
  [GENERAL_URL_ENUM.OTHER]: GENERAL_URL_ENUM.OTHER,
  [GENERAL_URL_ENUM.EXTERNAL]: GENERAL_URL_ENUM.EXTERNAL,
  [GENERAL_URL_ENUM.INTERNAL]: GENERAL_URL_ENUM.INTERNAL,
  [GENERAL_URL_ENUM.EXAMPLE]: GENERAL_URL_ENUM.EXAMPLE,
};

export function convertStringToGeneralURL(input: string): GENERAL_URL_TYPES {
  if (
    !GENERAL_URL_TYPE_ARRAY.includes(
      input.trim().toUpperCase() as GENERAL_URL_TYPES,
    )
  ) {
    throw new Error('Invalid GENERAL URL: ' + input);
  }
  return input.trim().toUpperCase() as GENERAL_URL_TYPES;
}

export function convertStringToGeneralURLes(
  input: string,
): GENERAL_URL_TYPES[] {
  const URLNames: string[] = input
    .split(',')
    .map((URL) => URL.trim().toUpperCase());
  const URLes: GENERAL_URL_TYPES[] = URLNames.filter((URLName) =>
    GENERAL_URL_TYPE_ARRAY.includes(URLName as GENERAL_URL_TYPES),
  ) as GENERAL_URL_TYPES[]; // Type assertion here
  return URLes;
}
