export type ITERATION_TYPES = 'SCRUM' | 'KANBAN';
export const ITERATION_TYPES = ['SCRUM', 'KANBAN'];
export const DEFAULT_ITERATION_TYPE = 'SCRUM';
export enum ITERATION_ENUM {
  SCRUM = 'SCRUM',
  KANBAN = 'KANBAN',
}
export const IterationMap = {
  [ITERATION_ENUM.SCRUM]: ITERATION_ENUM.SCRUM,
  [ITERATION_ENUM.KANBAN]: ITERATION_ENUM.KANBAN,
};