export type PROJECT_STATUS_TYPES = 'PLANNED' | 'IN_PROGRESS' | 'COMPLETED';
export const PROJECT_STATUS_TYPES = ['PLANNED', 'IN_PROGRESS', 'COMPLETED'];
export const DEFAULT_PROJECT_STATUS = 'PLANNED';
export enum PROJECT_STATUS_ENUM {
  PLANNED = 'PLANNED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
}
export const ProjectStatusMap = {
  [PROJECT_STATUS_ENUM.PLANNED]: PROJECT_STATUS_ENUM.PLANNED,
  [PROJECT_STATUS_ENUM.IN_PROGRESS]: PROJECT_STATUS_ENUM.IN_PROGRESS,
  [PROJECT_STATUS_ENUM.COMPLETED]: PROJECT_STATUS_ENUM.COMPLETED,
};
