export type TASK_STATUS_TYPES = 'TODO' | 'IN_PROGRESS' | 'DONE';
export const TASK_STATUS = ['TODO', 'IN_PROGRESS', 'DONE'];
export const DEFAULT_TASK_STATUS = 'TODO';
export enum TASK_STATUS_TYPES_ENUM {
  TODO = 'TODO',
  IN_PROGRESS = 'IN_PROGRESS',
  DONE = 'DONE',
}
export const TASK_STATUS_TYPES_MAP = {
  [TASK_STATUS_TYPES_ENUM.TODO]: TASK_STATUS_TYPES_ENUM.TODO,
  [TASK_STATUS_TYPES_ENUM.IN_PROGRESS]: TASK_STATUS_TYPES_ENUM.IN_PROGRESS,
  [TASK_STATUS_TYPES_ENUM.DONE]: TASK_STATUS_TYPES_ENUM.DONE,
};
